doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            product_product_id: 'App\Model\Product\Entity\Product\IdType'
            marketplace_partner_id: 'App\Model\Marketplace\Entity\Partner\IdType'
            marketplace_partner_email: 'App\Model\Marketplace\Entity\Partner\EmailType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Product:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Product/Entity'
                prefix: 'App\Model\Product\Entity'
                alias: Product
            Partner:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Marketplace/Entity'
                prefix: 'App\Model\Marketplace\Entity'
                alias: Partner

