version: '3.3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Nginx.Dockerfile
    ports:
      - '8099:80'
    depends_on:
      - fpm
    volumes:
      - ../:/var/www/app
  fpm:
    build:
      context: ./fpm
      dockerfile: Fpm.Dockerfile
    volumes:
      - ../:/var/www/app
      - composer:/root/.composer/cache
    depends_on:
      - pgsql
  pgsql:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marketplace
    ports:
      - '54321:5432'
    volumes:
      - pg-marketplace:/var/lib/postgresql/data

volumes:
  composer:
  pg-marketplace:
    external: true
